/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-10-14 08:04:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.sub2_005fTF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class TourFestivalList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1728863602318L));
    _jspx_dependants.put("jar:file:/C:/workspace/8_MyBatics/Skt/src/main/webapp/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./views/sub2_TF/css/TourFestivalList.css?after\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	 body {\r\n");
      out.write("      overflow-x: hidden;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("   }\r\n");
      out.write("   .nav-wrap a {\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   color: #000;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("	<br><br><br><br><br><br>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("    \r\n");
      out.write("         <!--  \r\n");
      out.write("        <div id=\"search-form\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th><p>지역별</p></th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select name=\"addressRegion\" id=\"addressRegion1\" name=\"color\" class=\"area1\"></select>\r\n");
      out.write("                        <select name=\"addressDo\" id=\"addressDo1\" name=\"color\" class=\"area1\"></select>\r\n");
      out.write("                        <select name=\"addressSiGunGu\" id=\"addressSiGunGu1\" name=\"color\" class=\"area1\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th><p>계절별</p></th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <div class=\"season\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"spring\" id=\"spring\" value=\"spring\">\r\n");
      out.write("                            <label for=\"spring\">#봄</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"summer\" id=\"summer\" value=\"summer\">\r\n");
      out.write("                            <label for=\"summer\">#여름</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"fall\" id=\"fall\" value=\"fall\">\r\n");
      out.write("                            <label for=\"fall\">#가을</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"winter\" id=\"winter\" value=\"winter\">\r\n");
      out.write("                            <label for=\"winter\">#겨울</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th><p>테마별</p></th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <div class=\"tema\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"history\" id=\"history\" value=\"history\">\r\n");
      out.write("                            <label for=\"history\">#역사</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"city\" id=\"city\" value=\"city\">\r\n");
      out.write("                            <label for=\"city\">#도시</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"natural\" id=\"natural\" value=\"natural\">\r\n");
      out.write("                            <label for=\"natural\">#자연</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"art\" id=\"art\" value=\"art\">\r\n");
      out.write("                            <label for=\"art\">#예술</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"healling\" id=\"healling\" value=\"healling\">\r\n");
      out.write("                            <label for=\"healling\">#힐링</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"dynamic\" id=\"dynamic\" value=\"dynamic\">\r\n");
      out.write("                            <label for=\"dynamic\">#다이나믹</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"./views/sub2_TF/TourFestivalList-area.js\"></script>\r\n");
      out.write("        -->\r\n");
      out.write("        \r\n");
      out.write("        <form action=\"search.tf\" class=\"search-box\" method=\"GET\">\r\n");
      out.write("            <div id=\"search-con\">\r\n");
      out.write("                <input type=\"hidden\" name=\"cpage\" value=\"1\">\r\n");
      out.write("                <!-- <select class=\"form-select me-2\" name=\"condition\">\r\n");
      out.write("                    <option value=\"tour\">관광지</option>\r\n");
      out.write("                    <option value=\"festival\">축제</option>\r\n");
      out.write("                </select> -->\r\n");
      out.write("                <input type=\"text\" class=\"form-control me-2\" name=\"keyword\"\r\n");
      out.write("                    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"검색어를 입력하세요\" \r\n");
      out.write("                    style=\"width: 480px;\r\n");
      out.write("                    height: 60px;\r\n");
      out.write("                    border-radius: 50px;\r\n");
      out.write("                    font-size: 20px;\r\n");
      out.write("                    font-weight: 800;\r\n");
      out.write("                    margin-left: 720px;\r\n");
      out.write("                    margin-top: 60px;\r\n");
      out.write("                    border: none;\r\n");
      out.write("                    padding-left: 20px;\">\r\n");
      out.write("                <div id=\"search-btn\">\r\n");
      out.write("                    <button type=\"submit\" class=\"search-btn\" style=\"width: 170px;\r\n");
      out.write("                    height: 55px;\r\n");
      out.write("                    margin-left: 870px;\r\n");
      out.write("                    border: none;\r\n");
      out.write("                    border-radius: 20px;\r\n");
      out.write("                    color: #fff;\r\n");
      out.write("                    font-size: 20px;\r\n");
      out.write("                    font-weight: 800;\r\n");
      out.write("                    background-color: #6FBAFF;\r\n");
      out.write("                    margin-top: 30px;\">검색</button>\r\n");
      out.write("                </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <br><br><br>\r\n");
      out.write("           <div class=\"content2\">\r\n");
      out.write("            <input type=\"radio\" name=\"content-tour\" id=\"ct\" checked>\r\n");
      out.write("            <label for=\"ct\">관광지</label>\r\n");
      out.write("            <input type=\"radio\" name=\"content-tour\" id=\"cf\">\r\n");
      out.write("            <label for=\"cf\">축제</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"content-box\" style=\"height: fit-content;\">\r\n");
      out.write("            <div class=\"list-box\" id=\"tour-content\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("         \r\n");
      out.write("            </div>\r\n");
      out.write("            <script>\r\n");
      out.write("	            function toggleLike(tourNo, button) {\r\n");
      out.write("	                const likeImg = button.querySelector('img'); // 버튼 내의 이미지 요소\r\n");
      out.write("	                const isLiked = likeImg.src.includes(\"Like_r.png\"); // 현재 상태 확인\r\n");
      out.write("	\r\n");
      out.write("	                const action = isLiked ? \"unlike\" : \"like\"; // 상태에 따라 액션 설정\r\n");
      out.write("	\r\n");
      out.write("	                $.ajax({\r\n");
      out.write("	                    url: '/skt/tourfestivallist.tf', // 요청할 URL\r\n");
      out.write("	                    method: 'POST', // 요청 방식\r\n");
      out.write("	                    data: { action: action, tourNo: tourNo }, // 전달할 데이터\r\n");
      out.write("	                    success: function(response) {\r\n");
      out.write("	                        // 서버 응답이 성공하면 이미지 변경\r\n");
      out.write("	                        likeImg.src = isLiked ? \"./views/sub2_TF/img/Like.png\" : \"./views/sub2_TF/img/Like_r.png\";\r\n");
      out.write("	                    },\r\n");
      out.write("	                    error: function() {\r\n");
      out.write("	                        alert('좋아요 상태를 변경하는 데 실패했습니다.');\r\n");
      out.write("	                    }\r\n");
      out.write("	                });\r\n");
      out.write("	            }\r\n");
      out.write("            </script>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"list-box\" id=\"festival-content\" style=\"display: none;\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        <script>\r\n");
      out.write("            // 탭 변경 시 내용 업데이트\r\n");
      out.write("            document.querySelectorAll('input[name=\"content-tour\"]').forEach((radio) => {\r\n");
      out.write("                radio.addEventListener('change', () => {\r\n");
      out.write("                    const isTourChecked = document.getElementById('ct').checked;\r\n");
      out.write("                    document.getElementById('tour-content').style.display = isTourChecked ? 'flex' : 'none';\r\n");
      out.write("                    document.getElementById('festival-content').style.display = isTourChecked ? 'none' : 'flex';\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("    \r\n");
      out.write("        </script>\r\n");
      out.write("    </div>\r\n");
      out.write("        <br><br><br>\r\n");
      out.write("    	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/sub2_TF/TourFestivalList.jsp(119,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("t");
      // /views/sub2_TF/TourFestivalList.jsp(119,12) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/sub2_TF/TourFestivalList.jsp(119,12) '${Tlist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Tlist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            <a href=\"detail.tf?tno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.tourNo}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                <div id=\"list-con\">\r\n");
            out.write("                    <div id=\"list-img\"><img src=\"./resource/tourThumb/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ t.tourImg}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"height: 300px; width: 300px;\"></div>\r\n");
            out.write("                    <h3>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.tourName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("                    <div id=\"under-area\">\r\n");
            out.write("                        <h5>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.tourArea}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("                        <button type=\"button\" onclick=\"toggleLike(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.tourNo}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(", this)\">\r\n");
            out.write("						    <img src=\"./views/sub2_TF/img/Like.png\" id=\"like-img-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.tourNo}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("						</button>\r\n");
            out.write("                    </div>\r\n");
            out.write("                </div>\r\n");
            out.write("                </a>\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /views/sub2_TF/TourFestivalList.jsp(157,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("f");
      // /views/sub2_TF/TourFestivalList.jsp(157,12) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/views/sub2_TF/TourFestivalList.jsp(157,12) '${Flist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Flist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            <a href=\"fesdatail.tf?fno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.fsNo}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                <div id=\"list-con\">\r\n");
            out.write("                    <div id=\"list-img\"><img src=\"./resource/festival/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ f.fsImg}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"height: 300px; width: 300px;\"></div>\r\n");
            out.write("                    <h3>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.fsName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("                    <div id=\"under-area\">\r\n");
            out.write("                        <h5>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.fsArea}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("                        <button type=\"button\">\r\n");
            out.write("                            <img src=\"./views/sub2_TF/img/Like.png\" class=\"like(this)\" onclick=\"like(this)\">\r\n");
            out.write("                        </button>\r\n");
            out.write("                    </div>\r\n");
            out.write("                </div>\r\n");
            out.write("                </a>\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
