/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-09-09 08:17:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class page_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>ì»¤ë®¤ëí°ë©ì¸</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-color: #ADE8F4;\r\n");
      out.write("        }\r\n");
      out.write("        .wrap {\r\n");
      out.write("            width: 1246px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            border: 1px solid black;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            box-shadow: 1px 1px 1px 1px rgb(203, 203, 203)\r\n");
      out.write("        }\r\n");
      out.write("        #header, #footer, #aside {\r\n");
      out.write("            height: 20%;\r\n");
      out.write("        }\r\n");
      out.write("        #header {\r\n");
      out.write("            width: 1284px;\r\n");
      out.write("            height: 91px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            box-shadow: 1px 1px 1px 1px rgb(203, 203, 203)\r\n");
      out.write("        }\r\n");
      out.write("        .main_image {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main_image_text {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 30%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translate(-50%, -50%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: 900;\r\n");
      out.write("            text-shadow: -1px 0px black, 0px 1px black, 1px 0px black, 0px -1px black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #search {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px; /* ê°ê²© ì¡°ì  */\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 80%;\r\n");
      out.write("            left: 55%;\r\n");
      out.write("            transform: translate( -30%, -50% );\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #searchKeyword {\r\n");
      out.write("            background-color: rgb(231, 231, 231);\r\n");
      out.write("            border-radius: 40px;\r\n");
      out.write("            border-style: none;\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            background-color: rgb(179, 179, 179);\r\n");
      out.write("            border-radius: 40px;\r\n");
      out.write("            border-style: none;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .createBtn {\r\n");
      out.write("            float: right;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            border-style: none;\r\n");
      out.write("            background-color: rgb(177, 192, 255);\r\n");
      out.write("            width: 90px;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .createBtn:hover {\r\n");
      out.write("            background-color: rgb(147, 169, 255);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            background-color: #9fd7ff; /* ì°í íëì */\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"header\"></div>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <div class=\"container mt-3\">\r\n");
      out.write("            <div class=\"main_image\">\r\n");
      out.write("                <img src=\"./img/ta.jpg\" style=\"width: 1221px; border-radius: 20px;\">\r\n");
      out.write("                <h1 class=\"main_image_text\" style=\"font-size:50px\">ì»¤ë®¤ëí°</h1>\r\n");
      out.write("                <div id=\"search\">\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <button type=\"button\" id=\"dropdownMenuButton\" class=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                            ì í\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\" onclick=\"updateDropdownText('ìì±ì')\">ìì±ì</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\" onclick=\"updateDropdownText('ì ëª©')\">ì ëª©</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\" onclick=\"updateDropdownText('ìì±ì¼')\">ìì±ì¼</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"text\" id=\"searchKeyword\" placeholder=\"í¤ìë ê²ì\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br>        \r\n");
      out.write("            <table class=\"table table-hover\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>ê¸ë²í¸</th>\r\n");
      out.write("                        <th>ì ëª©</th>\r\n");
      out.write("                        <th>ìì±ì</th>\r\n");
      out.write("                        <th>ì í</th>\r\n");
      out.write("                        <th>ì¡°íì</th>\r\n");
      out.write("                        <th>ìì±ì¼</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>ì²«ë²ì§¸ ê²ìê¸</td>\r\n");
      out.write("                        <td>user01</td>\r\n");
      out.write("                        <td>QnA</td>\r\n");
      out.write("                        <td>125</td>\r\n");
      out.write("                        <td>2024-01-01</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>2</td>\r\n");
      out.write("                        <td>ëë²ì§¸ ê²ìê¸</td>\r\n");
      out.write("                        <td>user02</td>\r\n");
      out.write("                        <td>ì¶ì²</td>\r\n");
      out.write("                        <td>33</td>\r\n");
      out.write("                        <td>2024-01-01</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>3</td>\r\n");
      out.write("                        <td>ì¸ë²ì§¸ ê²ìê¸</td>\r\n");
      out.write("                        <td>user03</td>\r\n");
      out.write("                        <td>ì¶ì²</td>\r\n");
      out.write("                        <td>9</td>\r\n");
      out.write("                        <td>2024-01-01</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>4</td>\r\n");
      out.write("                        <td>ë¤ë²ì§¸ ê²ìê¸</td>\r\n");
      out.write("                        <td>user04</td>\r\n");
      out.write("                        <td>QnA</td>\r\n");
      out.write("                        <td>89</td>\r\n");
      out.write("                        <td>2024-01-01</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>5</td>\r\n");
      out.write("                        <td>ë¤ì¯ë²ì§¸ ê²ìê¸</td>\r\n");
      out.write("                        <td>user05</td>\r\n");
      out.write("                        <td>QnA</td>\r\n");
      out.write("                        <td>305</td>\r\n");
      out.write("                        <td>2024-01-01</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <ul class=\"pagination justify-content-center\">\r\n");
      out.write("                <li class=\"page-item\"><a class=\"page-link\" href=\"javascript:void(0);\">ì´ì </a></li>\r\n");
      out.write("                <li class=\"page-item\"><a class=\"page-link\" href=\"javascript:void(0);\">1</a></li>\r\n");
      out.write("                <li class=\"page-item\"><a class=\"page-link\" href=\"javascript:void(0);\">2</a></li>\r\n");
      out.write("                <li class=\"page-item\"><a class=\"page-link\" href=\"javascript:void(0);\">3</a></li>\r\n");
      out.write("                <li class=\"page-item\"><a class=\"page-link\" href=\"javascript:void(0);\">4</a></li>\r\n");
      out.write("                <li class=\"page-item\"><a class=\"page-link\" href=\"javascript:void(0);\">5</a></li>\r\n");
      out.write("                <li class=\"page-item\"><a class=\"page-link\" href=\"javascript:void(0);\">ë¤ì</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <br>\r\n");
      out.write("            <button type=\"button\" class=\"createBtn\">ê¸ì°ê¸°</button>\r\n");
      out.write("            <br><br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function updateDropdownText(selectedText) {\r\n");
      out.write("            document.getElementById('dropdownMenuButton').textContent = selectedText;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
