/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-07 02:09:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberEnrollForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1727839533044L));
    _jspx_dependants.put("jar:file:/C:/workspace/9_Spring/spring/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원가입</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<!-- 메뉴바 -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"content\">\n");
      out.write("        <br><br>\n");
      out.write("        <div class=\"innerOuter\">\n");
      out.write("            <h2>회원가입</h2>\n");
      out.write("            <br>\n");
      out.write("\n");
      out.write("            <form action=\"insert.me\" method=\"post\" id=\"enrollForm\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"userId\">* ID : </label> \n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"userId\" placeholder=\"Please Enter ID\" name=\"userId\" required>\n");
      out.write("                    <div id=\"checkResult\" style=\"font-size:0.7em; display:none;\"></div>\n");
      out.write("					<br>\n");
      out.write("                    <label for=\"userPwd\">* Password : </label>\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"userPwd\" placeholder=\"Please Enter Password\" name=\"userPwd\" required> <br>\n");
      out.write("\n");
      out.write("                    <label for=\"checkPwd\">* Password Check : </label>\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"checkPwd\" placeholder=\"Please Enter Password\" required> <br>\n");
      out.write("\n");
      out.write("                    <label for=\"userName\">* Name : </label>\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"userName\" placeholder=\"Please Enter Name\" name=\"userName\" required> <br>\n");
      out.write("\n");
      out.write("                    <label for=\"email\"> &nbsp; Email : </label>\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"email\" placeholder=\"Please Enter Email\" name=\"email\"> <br>\n");
      out.write("\n");
      out.write("                    <label for=\"age\"> &nbsp; Age : </label>\n");
      out.write("                    <input type=\"number\" class=\"form-control\" id=\"age\" placeholder=\"Please Enter Age\" name=\"age\"> <br>\n");
      out.write("\n");
      out.write("                    <label for=\"phone\"> &nbsp; Phone : </label>\n");
      out.write("                    <input type=\"tel\" class=\"form-control\" id=\"phone\" placeholder=\"Please Enter Phone (-없이)\" name=\"phone\"> <br>\n");
      out.write("                    \n");
      out.write("                    <label for=\"address\"> &nbsp; Address : </label>\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"address\" placeholder=\"Please Enter Address\" name=\"address\"> <br>\n");
      out.write("                    \n");
      out.write("                    <label> &nbsp; Gender : </label> &nbsp;&nbsp;\n");
      out.write("                    <input type=\"radio\" id=\"Male\" value=\"M\" name=\"gender\" checked>\n");
      out.write("                    <label for=\"Male\">남자</label> &nbsp;&nbsp;\n");
      out.write("                    <input type=\"radio\" id=\"Female\" value=\"F\" name=\"gender\">\n");
      out.write("                    <label for=\"Female\">여자</label> &nbsp;&nbsp;\n");
      out.write("                </div> \n");
      out.write("                <br>\n");
      out.write("                <div class=\"btns\" align=\"center\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" disabled>회원가입</button>\n");
      out.write("                    <button type=\"reset\" class=\"btn btn-danger\">초기화</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        <br><br>\n");
      out.write("        <script>\n");
      out.write("            $(function() {\n");
      out.write("                const idInput = document.querySelector(\"#enrollForm input[name=userId]\");\n");
      out.write("\n");
      out.write("                let eventFlag;\n");
      out.write("\n");
      out.write("                idInput.onkeyup = function(ev) {    // 키가 입력될 때마다 호출\n");
      out.write("                    clearTimeout(eventFlag);    // 아직 실행되지 않은 ajax 요청을 취소\n");
      out.write("                    \n");
      out.write("                    const str = ev.target.value;\n");
      out.write("\n");
      out.write("                    if(str.trim().length >= 5) {\n");
      out.write("                    eventFlag = setTimeout(function(){  // 1초 뒤에 값을 확인해서 ajax 요청\n");
      out.write("                                    // ajax 요청\n");
      out.write("                                    $.ajax({\n");
      out.write("                                        url: \"idCheck.me\",\n");
      out.write("                                        data: {\n");
      out.write("                                            checkId : str\n");
      out.write("                                        },\n");
      out.write("                                        success: function(result) {\n");
      out.write("                                            const checkResult = document.querySelector(\"#checkResult\");\n");
      out.write("                                            checkResult.style.display = \"block\";\n");
      out.write("\n");
      out.write("                                            if(result === \"NNNNN\") {\n");
      out.write("                                                checkResult.style.color = \"red\";\n");
      out.write("                                                checkResult.innerText = \"이미 사용중인 아이디입니다.\"\n");
      out.write("\n");
      out.write("                                                document.querySelector(\"#enrollForm button[type='submit']\").disabled = true;\n");
      out.write("                                            } else {\n");
      out.write("                                                checkResult.style.color = \"green\";\n");
      out.write("                                                checkResult.innerText = \"사용 가능한 아이디입니다.\"\n");
      out.write("                                            \n");
      out.write("                                                document.querySelector(\"#enrollForm button[type='submit']\").disabled = false;\n");
      out.write("                                            }\n");
      out.write("                                         },\n");
      out.write("                                        error : function() {\n");
      out.write("                                            console.log(\"아이디 중복체크 ajax 실패\")\n");
      out.write("                                        }\n");
      out.write("                                    })\n");
      out.write("                                }, 1000) \n");
      out.write("                    } else {\n");
      out.write("                        document.querySelector(\"#enrollForm button[type='submit']\").disabled = true;\n");
      out.write("                        document.querySelector(\"#checkResult\").style.display = \"none\";\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("        </script>\n");
      out.write("     \n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 푸터바 -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
