/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-10-14 01:58:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class menubar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1728863602318L));
    _jspx_dependants.put("jar:file:/C:/workspace/8_MyBatics/Skt/src/main/webapp/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<style>\r\n");
      out.write("@font-face {\r\n");
      out.write("    font-family: 'NanumSquareRound';\r\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/NanumSquareRound.woff') format('woff');\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("  }\r\n");
      out.write("  @font-face {\r\n");
      out.write("    font-family: 'nanumL';\r\n");
      out.write("    src: url('font/NanumSquareRoundL.ttf');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("  }\r\n");
      out.write("  @font-face {\r\n");
      out.write("    font-family: 'nanumR';\r\n");
      out.write("    src: url('font/NanumSquareRoundR.ttf');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("  }\r\n");
      out.write("  @font-face {\r\n");
      out.write("    font-family: 'nanumB';\r\n");
      out.write("    src: url('font/NanumSquareRoundB.ttf');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("  }\r\n");
      out.write("  @font-face {\r\n");
      out.write("    font-family: 'nanumEB';\r\n");
      out.write("    src: url('font/NanumSquareRoundEB.ttf');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("<!-- 공통 css -->\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("   display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    background-color: #DFF0FF;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-wrap{\r\n");
      out.write("    width: 100vw;\r\n");
      out.write("    background-color: #DFF0FF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*menubar*/\r\n");
      out.write("#navi ul, li, ol {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    margin: 0px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navi a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#navigator {\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    margin-left: 16.5%;\r\n");
      out.write("    width: 1280px;\r\n");
      out.write("    height: 90px;\r\n");
      out.write("    z-index: 9999;   \r\n");
      out.write("    position: fixed;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navi {\r\n");
      out.write("    border: solid none;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.25);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navi > li {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 19%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navi  a {\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    font-weight: 900;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    line-height: 36px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#nav-menu1 {\r\n");
      out.write("    border: solid none;\r\n");
      out.write("    width: 55px;\r\n");
      out.write("    height: 55px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    background-color: #D9D9D9;\r\n");
      out.write("    margin-bottom: 55px;\r\n");
      out.write("    margin-right: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-menu2 {\r\n");
      out.write("    border: solid none;\r\n");
      out.write("    width: 55px;\r\n");
      out.write("    height: 55px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    background-color: #D9D9D9;\r\n");
      out.write("    margin-bottom: 55px;\r\n");
      out.write("    margin-right: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-content{\r\n");
      out.write("    margin-top: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navi img{\r\n");
      out.write("    width: 100px;  \r\n");
      out.write("    height: auto;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    margin-left:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navi a:hover {\r\n");
      out.write("    color: #868686;\r\n");
      out.write("    scale: 1.08;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navi a.nav-logo{\r\n");
      out.write("    scale: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navi>.nav-content>ul {\r\n");
      out.write("    display: none;\r\n");
      out.write("    padding: 15px 0;\r\n");
      out.write("    margin-top: -20px;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menubar-profile {\r\n");
      out.write("   margin-top: 10px;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navi>.nav-content>ul a {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navi>.nav-content>a:hover+ul {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 160px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border: solid #FFC2E2;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    border-radius: 40px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#navi>.nav-content>ul:hover {\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 160px;\r\n");
      out.write("    border: solid #FFC2E2;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    border-radius: 40px;\r\n");
      out.write("}\r\n");
      out.write(" .nav-wrap  hr{\r\n");
      out.write("   margin:15px;\r\n");
      out.write("    width: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"nav-wrap\">\r\n");
      out.write("        <div id=\"navigator\">\r\n");
      out.write("            <ul id=\"navi\">\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"nav-logo\">\r\n");
      out.write("                <img src=\"");
      out.print(contextPath );
      out.write("/views/common/img/logo_1.png\" alt=\"로고\" onclick href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"></a></li>\r\n");
      out.write("            \r\n");
      out.write("                <li class=\"nav-content\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/tourfestivallist.tf?cpage=1\">명소찾기</a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"");
      out.print(contextPath );
      out.write("/tourfestivallist.tf?cpage=1\">관광지/축제</a></li>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <li><a href=\"");
      out.print(contextPath );
      out.write("/intoMbti.co\">축MBTI</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-content\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/course.c?cpage=1\">여행코스</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-content\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/createMyCourseToPage.mc\">나만의 코스</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-content\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/board.bo?cpage=1\">커뮤니티</a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                ");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("             ");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /views/common/menubar.jsp(229,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty loginUser }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("              <!-- 로그인전 -->\r\n");
                  out.write("            <div id=\"nav-menu1\" class=\"nav-content\">\r\n");
                  out.write("            <a href=\"\"><img src=\"");
                  out.print(contextPath );
                  out.write("/views/common/img/login_logo.png\" alt=\"로그인 로고\" style=\"width: 35px; height: auto;\"></a>\r\n");
                  out.write("              <ul id=\"menubar-profile\">\r\n");
                  out.write("                       <li><a href='");
                  out.print(contextPath );
                  out.write("/intoLogin.co'>로그인</a></li>\r\n");
                  out.write("                        <hr>\r\n");
                  out.write("                        <li><a href=\"");
                  out.print(contextPath );
                  out.write("/intoRegister.co\">회원가입</a></li>\r\n");
                  out.write("                    </ul>\r\n");
                  out.write("                 </div>\r\n");
                  out.write("                  ");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\r\n");
            out.write("              ");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f0_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("              <!-- 로그인후 -->\r\n");
                  out.write("              <div id=\"nav-menu2\" class=\"nav-content\">\r\n");
                  out.write("              <a href=\"\"><img src=\"");
                  out.print(contextPath );
                  out.write("/views/common/img/login_logo.png\" alt=\"로그인 로고\" style=\"width: 35px; height: auto;\"></a>\r\n");
                  out.write("                    <ul>\r\n");
                  out.write("                        <li><a href=\"");
                  out.print(contextPath );
                  out.write("/myPageTest.me\">마이페이지</a></li>\r\n");
                  out.write("                        <hr>\r\n");
                  out.write("                        <li><a href=\"");
                  out.print(contextPath );
                  out.write("/logout.me\">로그아웃</a></li>\r\n");
                  out.write("                    </ul>\r\n");
                  out.write("                </div>\r\n");
                  out.write("                ");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
              _jspx_th_c_005fotherwise_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
            }
            out.write("\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
